# Conda environment for setting up a benchmark environment with the
# latest software (specific versions must be specified manually)
# This environment can be created with `conda env create --file environment.yml`
name: cta-benchmarks
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - ctapipe
  - jupyter
  - papermill
  - seaborn
  - pandas
  - eventio=0.18
